version: '3.8'

services:
  fastapi_server:
    container_name: fastapi_server
    build: ./
    restart: always
    command: "sh -c 'alembic upgrade head && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'"
    volumes:
      - ./app:/code/app
      - ./alembic.ini:/code/alembic.ini
      - ./alembic:/code/alembic
    ports:
      - 8000:8000
    expose:
      - "8000"
    env_file: ".env"
    depends_on:
      - database
  
  redis_server:
    container_name: redis_server
    image: "redis:alpine"
    restart: always
    expose:
      - "6379"
    env_file: .env

  database:
    image: bitnami/postgresql:13.3.0
    restart: always
    container_name: database
    env_file: ".env"
    user: root
    volumes:
      - db_docker:/bitnami/postgresql
    ports:
      - 5454:5432  # Remove this on production
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_HOST_AUTH_METHOD= "trust"
      - POSTGRESQL_POSTGRES_PASSWORD= ${DATABASE_PASSWORD}

volumes:
  db_docker: